[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lap>=0.5.12",
    "onnxruntime-gpu>=1.23.2",
    "tensorrt>=10.14.1.48.post1",
    "ultralytics>=8.3.227",
]
